import Link from 'next/link'
import Navigation from '@/components/Navigation'
import type { Era } from '@/data/timeline'
import { getEras } from '@/data/index'
import { t } from '@/i18n/ui'
import { isValidLocale, type Locale } from '@/i18n/config'

const aboutText = {
  en: [
    "The Museum of Photography is a virtual space dedicated to the history of one of humanity's most transformative mediums. From Nicéphore Niépce's first heliograph in 1826 to images generated by artificial intelligence, our collection traces two centuries of innovation, creation and transformation of the gaze.",
    "Each event presented in this museum has been chosen for its decisive impact on the evolution of the photographic medium. From the technical inventions that made photography possible, to the artistic movements that gave it its letters of nobility, to the cameras that democratized it — each piece tells an essential chapter of this history.",
    "Our ambition is to make this history accessible to all, in a refined and contemplative setting. As in a real museum, we favor space, light and visual silence to let images and narratives express themselves fully.",
    "This project is designed as an experience of discovery. Browse the timeline to follow the thread of time, or dive into an article to explore a key moment in photographic history.",
  ],
  fr: [
    "Le Musée de la Photographie est un espace virtuel dédié à l'histoire de l'un des médiums les plus transformateurs de l'humanité. De la première héliographie de Nicéphore Niépce en 1826 aux images générées par intelligence artificielle, notre collection retrace deux siècles d'innovation, de création et de transformation du regard.",
    "Chaque événement présenté dans ce musée a été choisi pour son impact décisif sur l'évolution du médium photographique. Des inventions techniques qui ont rendu la photographie possible, aux mouvements artistiques qui lui ont donné ses lettres de noblesse, en passant par les appareils qui l'ont démocratisée — chaque pièce raconte un chapitre essentiel de cette histoire.",
    "Notre ambition est de rendre cette histoire accessible à tous, dans un cadre épuré et contemplatif. Comme dans un véritable musée, nous privilégions l'espace, la lumière et le silence visuel pour laisser les images et les récits s'exprimer pleinement.",
    "Ce projet est conçu comme une expérience de découverte. Parcourez la chronologie pour suivre le fil du temps, ou plongez dans un article pour approfondir un moment clé de l'histoire photographique.",
  ],
}

const erasLabel = { en: 'Eras', fr: 'Les époques' }

export default async function AboutPage({
  params,
}: {
  params: Promise<{ lang: string }>
}) {
  const { lang } = await params
  const locale: Locale = isValidLocale(lang) ? lang : 'en'
  const eras = getEras(locale)
  const texts = aboutText[locale]

  function localePath(path: string) {
    return locale === 'fr' ? `/fr${path}` : path
  }

  return (
    <main className="min-h-screen bg-white">
      <Navigation lang={locale} />

      <div className="pt-14">
        <div className="max-w-[700px] mx-auto px-6 py-16">
          <h1
            className="text-[32px] text-[#1a1a1a] mb-10"
            style={{ fontFamily: 'var(--font-heading)', fontWeight: 400, lineHeight: 1.2 }}
          >
            {t(locale, 'nav.about')}
          </h1>

          <div className="space-y-6 text-[15px] text-[#444] leading-relaxed mb-14">
            {texts.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
          </div>

          <div>
            <h2
              className="text-[11px] uppercase tracking-[0.15em] text-[#999] mb-6"
              style={{ fontFamily: 'var(--font-body)', fontWeight: 400 }}
            >
              {erasLabel[locale]}
            </h2>
            <ul className="space-y-3">
              {eras.map((era: Era) => (
                <li key={era.id}>
                  <Link
                    href={localePath(`/timeline#${era.id}`)}
                    className="group flex items-baseline gap-3"
                  >
                    <span className="text-[13px] tabular-nums text-[#999]">
                      {era.startYear}–{era.endYear}
                    </span>
                    <span className="text-[15px] text-[#444] group-hover:text-[#1a1a1a] transition-colors">
                      {era.name}
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div className="mt-20 pt-8 border-t border-[#e5e5e5]">
            <p className="text-[12px] text-[#999]">
              {t(locale, 'site.title')} — 1826–{locale === 'fr' ? "aujourd'hui" : 'present'}
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}
